Events/Events.WebApplication/Models/Events/EventViewModel.cs
namespace Events.WebApplication.Models.Events
{
    public class EventViewModel
    {
        public string Title { get; set; }
    }
}

Events/Events.WebApplication/Controllers/EventsController.cs
namespace Events.WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using Events.Data;
    using Events.Model;
    using Microsoft.AspNet.Identity;
    using Model.Enumerations;
    using Models.Events;

    public class EventsController : Controller
    {
        private EventsDbContext context = new EventsDbContext();

        // GET: Events
        public ActionResult Index()
        {
            var events = context.Events.Include(e => e.Teams).ToList();

            var player = CurrentPlayer();

            ViewBag.CurrentPlayer = player;
            return View(events);
        }

        public ActionResult AllEvents()
        {
            var allEvents = context.Events.ToList();
            var allEventsViewModel = new List<EventViewModel>();

            foreach (var sportEvent in allEvents)
            {
                var eventViewModel = new EventViewModel();
                eventViewModel.Title = sportEvent.Title;
                allEventsViewModel.Add(eventViewModel);
            }


            return View(allEventsViewModel);
        }

        // GET: MyEvents
        public ActionResult MyEvents()
        {
            var userId = this.User.Identity.GetUserId();
            var events = context.Events.Where(e => e.Host.UserId == userId).Include(e => e.Teams).ToList();
            return View(events);
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventView = context.Events.Find(id);
            if (eventView == null)
            {
                return HttpNotFound();
            }
            return View(eventView);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event eventModel)
        {
            var errors = ModelState.Select(m => m.Value.Errors);
            if (!ModelState.IsValid)
            {
                return View(eventModel);
            }
            var player = CurrentPlayer();

            eventModel.HostId = player.PlayerId;
            eventModel.CreatedOn = DateTime.Now;
            //eventModel.StartTime = DateTime.Now;


            context.Events.Add(eventModel);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult JoinEvent(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var player = CurrentPlayer();

            var eventSearched = context.Events.Find(id);
            if (eventSearched == null)
            {
                return HttpNotFound();
            }
            //Player teams that fit the requirement of the event
            var playerTeams = player.MyTeams.Where(t => t.Players.Count == eventSearched.TeamMembersCapacity);
            ViewBag.Teams = playerTeams;
            return View((int)id);
        }

        [HttpPost]
        public ActionResult JoinEvent(int? id, int? TeamPicked)
        {
            if(id == null || TeamPicked == null)
            {
                return RedirectToAction("Index");
            }
            var eventToJoin = context.Events.Find(id.Value);
            if (eventToJoin == null)
            {
                return HttpNotFound();
            }
            
            var teamJoining = context.Teams.Find(TeamPicked.Value);
            if (teamJoining == null)
            {
                return HttpNotFound();
            }

            eventToJoin.Teams.Add(teamJoining);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult LeaveEvent(int id)
        {
            var player = CurrentPlayer();

            var eventToLeave = context.Events.Find(id);

            var eventTeams = eventToLeave.Teams.ToList();
            foreach (var team in eventTeams)
            {
                if (player.MyTeams.Contains(team))
                {
                    eventToLeave.Teams.Remove(team);
                }
            }


            context.SaveChanges();

            return RedirectToAction("Index");
        }


        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventToEdit = context.Events.Find(id);
            if (eventToEdit == null)
            {
                return HttpNotFound();
            }
            return View(eventToEdit);
        }

        // POST: Events/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event eventModel)
        {
            if (!ModelState.IsValid)
            {
                return View(eventModel);
            }

            context.Entry(eventModel).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventToDelete = context.Events.Find(id);
            if (eventToDelete == null)
            {
                return HttpNotFound();
            }
            return View(eventToDelete);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event eventToDelete = context.Events.Find(id);
            context.Events.Remove(eventToDelete);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult MatchAssembles(int id)
        {
            var currentEvent = context.Events.Find(id);

            var allEventTeams = currentEvent.Teams.ToList();


            var allMatchesForCurrentEvent = this.GenerateEventMatches(allEventTeams, id);

            foreach (var match in allMatchesForCurrentEvent)
            {
                currentEvent.MatchStatistics.Add(match);

            }

            context.SaveChanges();

            return RedirectToAction("Index");
        }
        //    return RedirectToAction("DisplayAllEventMatches", id);
        //}

        public ActionResult EventMatches(int id)
        {
            var currentEvent = this.context.Events.Find(id);

            return View(currentEvent);
        }


        private List<Match> GenerateEventMatches(List<Team> teams, int eventID)
        {
            var matches = new List<Match>();
            var teamsToChange = teams.ToList();
            //var firstTeam = teamsToChange.First();
            for (int i = 0, j = teamsToChange.Count; i < j; i++)
            {
                var firstTeam = teamsToChange.First();
                teamsToChange.Remove(firstTeam);
                matches.AddRange(GenerateMatches(teamsToChange, firstTeam, eventID));
            }
            return matches;
        }

        private List<Match> GenerateMatches(List<Team> teamsToPlayWith, Team teamFirst, int eventId)
        {
            var matches = new List<Match>();
            foreach (var team in teamsToPlayWith)
            {
                var match = new Match();
                match.HomeTeam = teamFirst;
                match.GuestTeam = team;
                match.EventId = eventId;
                matches.Add(match);
            }
            return matches;
        }

        private Player CurrentPlayer()
        {
            var userId = this.User.Identity.GetUserId();
            var player = context.Players.FirstOrDefault(p => p.UserId == userId);
            return player;
        }

    }
}

Events/Events.WebApplication/Views/Events/AllEvents.cshtml
@model IEnumerable<Events.WebApplication.Models.Events.EventViewModel>

@foreach (var sportEvent in Model)
{
    <div>
        <p>@sportEvent.Title</p>
    </div>
}

Events/Events.WebApplication/Views/Events/Create.cshtml
@model Events.Model.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(e => e.PredefinedSport, "Choose sport", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(e => e.PredefinedSport, "Predefined sport", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(e => e.PredefinedSport, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfTeams, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfTeams, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfTeams, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamMembersCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamMembersCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamMembersCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control datetimepicker", id = "datetimepicker" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(e => e.TypeOfMatchAssemble, "Type of match assemble", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(e => e.TypeOfMatchAssemble, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(e => e.TypeOfMatchAssemble, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Events/Events.WebApplication/Views/Events/Delete.cshtml
@model Events.Model.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Host.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Host.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PredefinedSport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PredefinedSport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfTeams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfTeams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamMembersCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamMembersCapacity)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfMatchAssemble)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfMatchAssemble)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" }) |
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Events/Events.WebApplication/Views/Events/Details.cshtml
@model Events.Model.Event

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Host.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Host.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PredefinedSport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PredefinedSport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfTeams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfTeams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamMembersCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamMembersCapacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfMatchAssemble)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeOfMatchAssemble)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }, new { @class = "btn btn-default"}) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default"})
</p>

Events/Events.WebApplication/Views/Events/Edit.cshtml
@model Events.Model.Event

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(e => e.PredefinedSport, "Choose sport", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(e => e.PredefinedSport, "Predefined sport", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(e => e.PredefinedSport, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfTeams, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfTeams, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfTeams, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamMembersCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeamMembersCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamMembersCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfMatchAssemble, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TypeOfMatchAssemble, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeOfMatchAssemble, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            @Html.HiddenFor(model => model.CreatedOn)
            @Html.HiddenFor(model => model.HostId)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Events/Events.WebApplication/Views/Events/EventMatches.cshtml
@model Events.Model.Event

@{
    ViewBag.Title = "MatchAssembles";
}

<h2>MatchAssembles</h2>

<table class="table">
    <tr>
        <th>
            Home Team names
        </th>
        <th>
            Guest Team Name
        </th>
    </tr>
    @foreach (var item in Model.MatchStatistics)
    {
        <tr>
            <td>
                @item.HomeTeam.Name
            </td>
            <td>
                @item.GuestTeam.Name
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to List", "Index", "Events", null, new { @class = "btn btn-default" })
</div>

Events/Events.WebApplication/Views/Events/Index.cshtml
@model IEnumerable<Events.Model.Event>

@{
    ViewBag.Title = "All events";
}

<h2>All events</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfTeams)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamMembersCapacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfMatchAssemble)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teams)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.NumberOfTeams)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.TeamMembersCapacity)
            </th>
            
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfMatchAssemble)
            </td>
            <td>
                <ul>
                    @foreach (var team in item.Teams)
                    {
                        <li>
                            @team.Name
                        </li>
                    }
                </ul>
            </td>
            <td>
                <div class="btn-group">
                    @if (item.Host != ViewBag.CurrentPlayer)
                    {
                        //ToDO : FIx the linq to return bool
                        var isNotInTheEvent = item.Teams.Any(e => e.Players.Contains(ViewBag.CurrentPlayer));
                        if (!isNotInTheEvent)
                        {
                            @Html.ActionLink("Join event", "JoinEvent", new { id = item.EventId }, new { @class = "btn btn-default" })
                            @Html.ActionLink("Details", "Details", new { id = item.EventId }, new { @class = "btn btn-default" })
                        }
                        else
                        {
                            @Html.ActionLink("Leave event", "LeaveEvent", new { id = item.EventId }, new { @class = "btn btn-default" })
                            @Html.ActionLink("Details", "Details", new { id = item.EventId }, new { @class = "btn btn-default" })
                        }
                    }
                    else
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.EventId }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Details", "Details", new { id = item.EventId }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.EventId }, new { @class = "btn btn-default" })
                    }
                    
                </div>
            </td>
            <td>
                @Html.ActionLink("Show matches", "EventMatches", new { id = item.EventId }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to List", "Index", "Home", null, new { @class = "btn btn-default" })
</div>

Events/Events.WebApplication/Views/Events/JoinEvent.cshtml
@{
    ViewBag.Title = "Join Event";
}

<h2>Join Event</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Hidden("id", "id")
    if (ViewBag.Teams == null)
    {
        @Html.DisplayText("You currently don't have team with which you can join this event")
    }
    else
    {
        <div class="form-group">
            @Html.DropDownList("TeamPicked", new SelectList(ViewBag.Teams, "TeamId", "Name"), new { @class = "form-control" })

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Join" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index", "Events", null, new { @class = "btn btn-default" })
    </div>

}

Events/Events.WebApplication/Views/Events/MyEvents.cshtml
@model IEnumerable<Events.Model.Event>

@{
    ViewBag.Title = "My events";
}

<h2>My events</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfTeams)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamMembersCapacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfMatchAssemble)
        </th>
        <th></th>
    </tr>
    
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.NumberOfTeams)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.TeamMembersCapacity)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfMatchAssemble)
            </td>
            <td>
                <div class="btn-group">
                    @Html.ActionLink("Edit", "Edit", new { id = item.EventId }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Details", "Details", new { id = item.EventId }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.EventId }, new { @class = "btn btn-default" })
                </div>
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to List", "Index", "Home", null, new { @class = "btn btn-default" })
</div>